_target_: src.model.sioconv.SioConv
_partial_: True
dim: 2048
depth: 24
dim_ff_hidden: 4096
dim_qk: 128
dim_v: 512
num_head: 8
chunk_size: 512
dropout: 0.1
dtype:
  _target_: hydra.utils.get_object
  path: torch.float