_target_: src.model.sioconv.SioConv
_partial_: True
dim: 1024
depth: 24
dim_ff_hidden: 2048
dim_qk: 256
dim_v: 256
num_head: 12
chunk_size: 512
dropout: 0.1
dtype:
  _target_: hydra.utils.get_object
  path: torch.float