weight: "weight/weight.ckpt"
context_len: 1
max_len: 1024
temperature: 1.0
devices:
  - 'cuda:0'
  - 'cuda:1'
  - 'cuda:2'
  - 'cuda:3'
  - 'cuda:4'
  - 'cuda:5'
dtype:
  _target_: hydra.utils.get_object
  path: torch.float