length: 1024
batch_size: 6
max_epochs: 1
save_every_n_steps: 5000
backup_every_n_steps: 500
refresh_every_n_steps: 8
text: "text/text.txt"
weight: "weight/weight.ckpt"
pipeline_checkpoint: 'never'
#pipeline_checkpoint: 'except_last'
out_only_device: false
devices:
  - 'cuda:0'
  - 'cuda:1'
  - 'cuda:2'
  - 'cuda:3'

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4

#scheduler:
  #_target_: timm.scheduler.cosine_lr.CosineLRScheduler
  #_partial_: true
  #warmup_t: 300
  #warmup_lr_init: 1e-5
  #cycle_limit: 65536
  #t_initial: 2000
  #warmup_prefix: false
  #cycle_mul: 1.0
  #lr_min: 5e-6

scheduler:
  _target_: src.scheduler.InvPropDecay
  _partial_: True
  decay_time: 1000