length: 1024
batch_size: 8
max_epochs: 1
save_every_n_steps: 10000
backup_every_n_steps: 100
text: "text/text.txt"
weight: "weight/weight.ckpt"
lr: 1e-5
devices:
  - 'cuda:0'
  - 'cuda:1'
  - 'cuda:2'
  - 'cuda:3'