length: 1024
batch_size: 2
max_epochs: 1
save_every_n_steps: 5000
backup_every_n_steps: 500
refresh_every_n_steps: 8
text: "text/text.txt"
weight: "weight/weight.ckpt"
lr: 1e-5
pipeline_checkpoint: 'never'
#pipeline_checkpoint: 'except_last'
out_only_device: false
devices:
  - 'cuda:0'
  - 'cuda:1'
  - 'cuda:2'
  - 'cuda:3'